from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import time
import logging
import json
from core.semantic_cache import SemanticCache
from core.mobility_engine import MobilityEngine

# Configure Logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler("mobility_system.log"),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger("MobilityAssistant")

app = FastAPI(title="Sustainable Smart Mobility Assistant API")

# Enable CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize Core Services
cache = SemanticCache()
engine = MobilityEngine()

class QueryRequest(BaseModel):
    query: str

class QueryResponse(BaseModel):
    query: str
    response: dict
    cache_status: str
    similarity_score: float
    total_latency: float
    explanation: str

@app.get("/")
async def root():
    return {"message": "Mobility Assistant API is running"}

@app.post("/query", response_model=QueryResponse)
async def handle_query(request: QueryRequest):
    start_time = time.time()
    query = request.query

    # 1. Check Cache
    cache_result = cache.search(query)
    
    if cache_result:
        end_time = time.time()
        latency = round(end_time - start_time, 4)
        
        logger.info(json.dumps({
            "event": "query_processed",
            "query": query,
            "status": "HIT",
            "similarity": cache_result['similarity'],
            "latency": latency
        }))

        return QueryResponse(
            query=query,
            response=cache_result['response'],
            cache_status='HIT',
            similarity_score=cache_result['similarity'],
            total_latency=latency,
            explanation=cache_result['explanation']
        )

    # 2. Cache MISS -> Call Engine
    engine_response = engine.process_query(query)
    
    # 3. Update Cache
    cache.update(query, engine_response)
    
    end_time = time.time()
    latency = round(end_time - start_time, 4)
    
    logger.info(json.dumps({
        "event": "query_processed",
        "query": query,
        "status": "MISS",
        "latency": latency
    }))

    return QueryResponse(
        query=query,
        response=engine_response,
        cache_status='MISS',
        similarity_score=1.0, 
        total_latency=latency,
        explanation="No sufficiently similar past query was found. A new response has been generated by the Mobility Engine."
    )

@app.get("/metrics")
async def get_metrics():
    metrics = cache.get_metrics()
    logger.info(f"Metrics Requested: {metrics}")
    return metrics

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
